<<<<<<< HEAD
baseurl: https://hxie13.github.io/cppLearn/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Xie Hui
=======
baseurl: https://hxie13.github.io/cppLearn
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Example Site
>>>>>>> 1e709297317f4256503b907649b6351089ce62a3

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
<<<<<<< HEAD
        - posts
=======
        - post
>>>>>>> 1e709297317f4256503b907649b6351089ce62a3
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
<<<<<<< HEAD
        subtitle: keep study, keep smile
        avatar:
            local: true
            src: img/avatar.jpg

    article:
        math: true
=======
        subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
>>>>>>> 1e709297317f4256503b907649b6351089ce62a3
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
<<<<<<< HEAD
            enabled: true
            local: true
            src: img/avatar.png
=======
            enabled: false
            local: false
            src:
>>>>>>> 1e709297317f4256503b907649b6351089ce62a3

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
<<<<<<< HEAD
          url: home
=======
          url: /
>>>>>>> 1e709297317f4256503b907649b6351089ce62a3
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
